#!/bin/bash

DIR2="$HOME/.local/bin"

Menu="$(ls -a $DIR2 | uniq -u | fzf --prompt="Which Program Would You Like To Run : " --border=rounded --margin=5% --color=dark --height 100% --reverse --header="                    PROGRAMS " --info=hidden --header-first)"

alacritty -e nvim $Menu

